# action.yml
name: 'Register Workflow with Prefect Cloud'
inputs:
  env:
    description: 'Environment to deploy Workflow'
    required: true
  git_url:
    description: 'Url of workflow Git repository'
    required: true
  branch_name:
    description: 'Branch name where workflow must be found'
    required: true
  commit_sha:
    description: 'Commit SHA'
    required: true
  workflow_path:
    description: 'Path to the workflow in the repository'
    required: true
  prefect_workflow_register_token:
    description: 'Prefect token to register workflows'
    required: true
  prefect_execution_environment:
    description: 'Prefect execution environment. E.g: ecs_fargate, kubernetes'
    required: true
  workflow_cpu_configuration:
    description: 'Workflow CPU configuration'
    required: true
    default: 512
  workflow_memory_configuration:
    description: 'Workflow Memory configuration'
    required: true
    default: 1024
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.env }}
    - ${{ inputs.git_url }}
    - ${{ inputs.branch_name }}
    - ${{ inputs.commit_sha }}
    - ${{ inputs.workflow_path }}
    - ${{ inputs.prefect_workflow_register_token }}
    - ${{ inputs.prefect_execution_environment }}
    - ${{ inputs.workflow_cpu_configuration }}
    - ${{ inputs.workflow_memory_configuration }}